ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-10_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-10_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-10_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-10_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-10.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-10.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-11_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-11_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-11_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-11_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-11.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-11.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-12_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-12_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-12_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-12_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-12.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-12.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-13_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-13_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-13_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-13_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-5_compact.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-5_compact.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-5.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-5.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-6_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-6_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-6_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-6_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-6.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-6.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-7_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-7_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-7_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-7_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-7.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-7.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-8.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-8.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-9_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-9_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-9_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-9_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Chapter-9.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Chapter-9.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_10-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_10-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-A_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-A_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_11-A_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_11-A_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_12-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_12-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-6_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-6_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-6_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-6_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-7_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-7_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-7_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-7_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-8_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-8_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_5-8_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_5-8_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_6-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_6-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_7-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_7-5_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-1_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-1_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-1_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-1_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-2_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-2_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-2_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-2_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-3_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-3_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-3_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-3_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-4_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-4_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-4_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-4_full.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-5_comp.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-5_comp.pdf
ln -s /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/slides/Section_9-5_full.pdf /home/lechen/Dropbox/Teaching/svn_teaching/2021_Spring_Math362/vimwiki_html/Section_9-5_full.pdf
