
let @a='y$A pF.i-neg0iconvert -negate :wj0'

convert -negate 1920px-Gamma_distribution_pdf.svg.png 1920px-Gamma_distribution_pdf.svg-neg.png
convert -negate 1920px-StudentizedRangePDF.svg.png 1920px-StudentizedRangePDF.svg-neg.png
convert -negate 2880px-Linear_regression.svg.png negate 2880px-Linear_regression.svg-neg.png
convert -negate alpha-beta.png alpha-beta-neg.png
convert -negate AMS-LeChen-20191029.png AMS-LeChen-20191029-neg.png
convert -negate AMS-LeChen-Citation-20191029-2.png AMS-LeChen-Citation-20191029-2-neg.png
convert -negate AMS-LeChen-Citation-20191029.png AMS-LeChen-Citation-20191029-neg.png
convert -negate AMS-LeChen-Citation.png AMS-LeChen-Citation-neg.png
convert -negate AMS-LeChen.png AMS-LeChen-neg.png
convert -negate ANOVA_Illustration.png ANOVA_Illustration-neg.png
convert -negate Bernoulli-neg.png Bernoulli-neg-neg.png
convert -negate Bernoulli.png Bernoulli-neg.png
convert -negate Beta_distribution_pdf.png Beta_distribution_pdf-neg.png
convert -negate cartoon_guide_regression.png cartoon_guide_regression-neg.png
convert -negate Case_11-3-1-Density.png Case_11-3-1-Density-neg.png
convert -negate Case_11-3-1-Outliers1.png Case_11-3-1-Outliers1-neg.png
convert -negate Case_11-3-1-Outliers2.png Case_11-3-1-Outliers2-neg.png
convert -negate Case_11-3-1-Outliers.png Case_11-3-1-Outliers-neg.png
convert -negate Case_11-3-1-Scatter.png Case_11-3-1-Scatter-neg.png
convert -negate Case_11-3-2-Sol.png Case_11-3-2-Sol-neg.png
convert -negate Case_12-2-1-1.png Case_12-2-1-1-neg.png
convert -negate Case_12-2-1-2.png Case_12-2-1-2-neg.png
convert -negate Case_12-2-1-diagnostic_plots1.png Case_12-2-1-diagnostic_plots1-neg.png
convert -negate Case_12-2-1-diagnostic_plots2.png Case_12-2-1-diagnostic_plots2-neg.png
convert -negate Case_12-2-1-diagnostic_plots.png Case_12-2-1-diagnostic_plots-neg.png
convert -negate Case_12-2-1-ggboxplot.png Case_12-2-1-ggboxplot-neg.png
convert -negate Case_12-2-1-ggline.png Case_12-2-1-ggline-neg.png
convert -negate Case_12-3-1-Sol1.png Case_12-3-1-Sol1-neg.png
convert -negate Case_7-5-2-2.png Case_7-5-2-2-neg.png
convert -negate Case_7-5-2.png Case_7-5-2-neg.png
convert -negate Casse_7-5-2.png Casse_7-5-2-neg.png
convert -negate Correlation_coefficent_Formula.png Correlation_coefficent_Formula-neg.png
convert -negate Correlation_coefficent.png Correlation_coefficent-neg.png
convert -negate diagnostic_plots.png diagnostic_plots-neg.png
convert -negate Eq_11-3-6-2.png Eq_11-3-6-2-neg.png
convert -negate Eq_11-3-6-3.png Eq_11-3-6-3-neg.png
convert -negate Eq_11-3-6.png Eq_11-3-6-neg.png
convert -negate Eq_12-2-1.png Eq_12-2-1-neg.png
convert -negate Ex_12-2-2.png Ex_12-2-2-neg.png
convert -negate Ex_7-4-19.png Ex_7-4-19-neg.png
convert -negate Ex_7-5-16.png Ex_7-5-16-neg.png
convert -negate Ex_9-3-3.png Ex_9-3-3-neg.png
convert -negate Ex_9-3-5.png Ex_9-3-5-neg.png
convert -negate EX_9-5-2.png EX_9-5-2-neg.png
convert -negate Example_11-3-2-1.png Example_11-3-2-1-neg.png
convert -negate Example_11-3-2-2.png Example_11-3-2-2-neg.png
convert -negate Example_11-3-2.png Example_11-3-2-neg.png
convert -negate Example-5-3-2.png Example-5-3-2-neg.png
convert -negate Example-5-3-4.png Example-5-3-4-neg.png
convert -negate Example-5-8-2-2.png Example-5-8-2-2-neg.png
convert -negate Example-5-8-2.png Example-5-8-2-neg.png
convert -negate Example-5-8-3.png Example-5-8-3-neg.png
convert -negate Example_6-4-3_1.png Example_6-4-3_1-neg.png
convert -negate Example_6-4-3_2.png Example_6-4-3_2-neg.png
convert -negate EYX.png EYX-neg.png
convert -negate EYX_Pred.png EYX_Pred-neg.png
convert -negate F-distribution_pdf.png F-distribution_pdf-neg.png
convert -negate Features2.png Features2-neg.png
convert -negate Features.png Features-neg.png
convert -negate Figure_10-2-2.png Figure_10-2-2-neg.png
convert -negate Figure_10-3-4.png Figure_10-3-4-neg.png
convert -negate Figure_11-2-10.png Figure_11-2-10-neg.png
convert -negate Figure_11-2-1.png Figure_11-2-1-neg.png
convert -negate Figure_11-2-2.png Figure_11-2-2-neg.png
convert -negate Figure_11-2-3.png Figure_11-2-3-neg.png
convert -negate Figure_11-2-4.png Figure_11-2-4-neg.png
convert -negate Figure_11-2-7.png Figure_11-2-7-neg.png
convert -negate Figure_11-2-8.png Figure_11-2-8-neg.png
convert -negate Figure_11-2-9.png Figure_11-2-9-neg.png
convert -negate Figure_11-3-2.png Figure_11-3-2-neg.png
convert -negate Figure_11-3-3.png Figure_11-3-3-neg.png
convert -negate Figure_11-3-4.png Figure_11-3-4-neg.png
convert -negate Figure_11-3-5.png Figure_11-3-5-neg.png
convert -negate Figure_12-2-1.png Figure_12-2-1-neg.png
convert -negate Figure_12-2-2.png Figure_12-2-2-neg.png
convert -negate Figure_12-2-3.png Figure_12-2-3-neg.png
convert -negate Figure_12-3-1.png Figure_12-3-1-neg.png
convert -negate figure-5-2-2.png figure-5-2-2-neg.png
convert -negate Figure-5-3-2.png Figure-5-3-2-neg.png
convert -negate Figure-5-4-2.png Figure-5-4-2-neg.png
convert -negate Figure-5-4-3.png Figure-5-4-3-neg.png
convert -negate Figure-6-3-1.png Figure-6-3-1-neg.png
convert -negate Figure-6-4-5.png Figure-6-4-5-neg.png
convert -negate Figure-6-4-6.png Figure-6-4-6-neg.png
convert -negate Figure-6-4-7.png Figure-6-4-7-neg.png
convert -negate Figure-6-4-8.png Figure-6-4-8-neg.png
convert -negate Figure_7-2-1.png Figure_7-2-1-neg.png
convert -negate Figure_7-3-1.png Figure_7-3-1-neg.png
convert -negate Figure_7-3-2.png Figure_7-3-2-neg.png
convert -negate Figure_7-4-1.png Figure_7-4-1-neg.png
convert -negate Figure_7-4-2.png Figure_7-4-2-neg.png
convert -negate Figure_7-5-1.png Figure_7-5-1-neg.png
convert -negate Figure_7-5-2.png Figure_7-5-2-neg.png
convert -negate Figure_9-2-1.png Figure_9-2-1-neg.png
convert -negate Figure_9-3-1.png Figure_9-3-1-neg.png
convert -negate Figure_9-3-2.png Figure_9-3-2-neg.png
convert -negate Figure_Example-10-3-1.png Figure_Example-10-3-1-neg.png
convert -negate Figure_Example-3-1.png Figure_Example-3-1-neg.png
convert -negate Fisher.png Fisher-neg.png
convert -negate Free-Pint-of-Guinness.png Free-Pint-of-Guinness-neg.png
convert -negate Future_obs-1.png Future_obs-1-neg.png
convert -negate Future_obs-2.png Future_obs-2-neg.png
convert -negate Gauss.png Gauss-neg.png
convert -negate Geometric.png Geometric-neg.png
convert -negate Goodness_fit_test_puzzle.png Goodness_fit_test_puzzle-neg.png
convert -negate HW_6-5-5.png HW_6-5-5-neg.png
convert -negate HW_9-2-1.png HW_9-2-1-neg.png
convert -negate HW_9-2-20.png HW_9-2-20-neg.png
convert -negate Inference_EYX-1.png Inference_EYX-1-neg.png
convert -negate Inference_EYX-2.png Inference_EYX-2-neg.png
convert -negate Iris_Dataset_Fisher2.png Iris_Dataset_Fisher2-neg.png
convert -negate Laplace.png Laplace-neg.png
convert -negate Linear_Regression.png Linear_Regression-neg.png
convert -negate Method4.png Method4-neg.png
convert -negate Methods2.png Methods2-neg.png
convert -negate Methods3.png Methods3-neg.png
convert -negate Methods5.png Methods5-neg.png
convert -negate Methods.png Methods-neg.png
convert -negate Midterm1.png Midterm1-neg.png
convert -negate Midterm2.png Midterm2-neg.png
convert -negate myplot.png myplot-neg.png
convert -negate Nonlinear_regression.png Nonlinear_regression-neg.png
convert -negate Normal_Distribution_PDF.png Normal_Distribution_PDF-neg.png
convert -negate Normal_List_Properties.png Normal_List_Properties-neg.png
convert -negate Proof_Theorem_11-3-1.png Proof_Theorem_11-3-1-neg.png
convert -negate Proof-Theorem-7-3-4.png Proof-Theorem-7-3-4-neg.png
convert -negate Proof_Thm-7-3-1.png Proof_Thm-7-3-1-neg.png
convert -negate Proof_Thm_7-3-3_1.png Proof_Thm_7-3-3_1-neg.png
convert -negate Proof_Thm_7-3-3_2.png Proof_Thm_7-3-3_2-neg.png
convert -negate Rplot001.png Rplot001-neg.png
convert -negate Rplot002.png Rplot002-neg.png
convert -negate Student.png Student-neg.png
convert -negate Student_t_pdf.png Student_t_pdf-neg.png
convert -negate Table_10-3-1.png Table_10-3-1-neg.png
convert -negate Table_10-3-2-2.png Table_10-3-2-2-neg.png
convert -negate Table_10-3-2.png Table_10-3-2-neg.png
convert -negate Table_10-3-4.png Table_10-3-4-neg.png
convert -negate Table_10-3-5.png Table_10-3-5-neg.png
convert -negate Table_10-3-6.png Table_10-3-6-neg.png
convert -negate Table_10-3-7.png Table_10-3-7-neg.png
convert -negate Table_10-4-1-1.png Table_10-4-1-1-neg.png
convert -negate Table_10-4-1.png Table_10-4-1-neg.png
convert -negate Table_10-4-2-1.png Table_10-4-2-1-neg.png
convert -negate Table_10-4-2.png Table_10-4-2-neg.png
convert -negate Table_10-4-3.png Table_10-4-3-neg.png
convert -negate Table_10-5-5.png Table_10-5-5-neg.png
convert -negate Table_10-5-6.png Table_10-5-6-neg.png
convert -negate Table_10-5-7.png Table_10-5-7-neg.png
convert -negate Table_10-5-8.png Table_10-5-8-neg.png
convert -negate Table_10-5-9.png Table_10-5-9-neg.png
convert -negate Table_11-2-10.png Table_11-2-10-neg.png
convert -negate Table_11-2-1.png Table_11-2-1-neg.png
convert -negate Table_11-2-2.png Table_11-2-2-neg.png
convert -negate Table_11-2-3.png Table_11-2-3-neg.png
convert -negate Table_11-2-5.png Table_11-2-5-neg.png
convert -negate Table_11-2-6.png Table_11-2-6-neg.png
convert -negate Table_11-2-7.png Table_11-2-7-neg.png
convert -negate Table_11-2-8.png Table_11-2-8-neg.png
convert -negate Table_11-2-9.png Table_11-2-9-neg.png
convert -negate Table_11-3-1.png Table_11-3-1-neg.png
convert -negate Table_11-3-2.png Table_11-3-2-neg.png
convert -negate Table_11-3-3.png Table_11-3-3-neg.png
convert -negate Table_12-1-1.png Table_12-1-1-neg.png
convert -negate Table_12-2-1.png Table_12-2-1-neg.png
convert -negate Table_12-3-1.png Table_12-3-1-neg.png
convert -negate Table_12-3-2.png Table_12-3-2-neg.png
convert -negate Table_13-2-1.png Table_13-2-1-neg.png
convert -negate Table_13-2-2.png Table_13-2-2-neg.png
convert -negate Table-5-8-1.png Table-5-8-1-neg.png
convert -negate Table_7-4-1.png Table_7-4-1-neg.png
convert -negate Table_7-4-3.png Table_7-4-3-neg.png
convert -negate Table_7-4-4.png Table_7-4-4-neg.png
convert -negate Table_7-4-5.png Table_7-4-5-neg.png
convert -negate Table_8-1-1.png Table_8-1-1-neg.png
convert -negate Table_9-2-1.png Table_9-2-1-neg.png
convert -negate Table_9-2-4.png Table_9-2-4-neg.png
convert -negate Table_9-3-1.png Table_9-3-1-neg.png
convert -negate Table_9-4-1.png Table_9-4-1-neg.png
convert -negate Theorem_11-3-9.png Theorem_11-3-9-neg.png
convert -negate Theorem-3-8-4.png Theorem-3-8-4-neg.png
convert -negate T-Statistics.png T-Statistics-neg.png
convert -negate Two_sample_test.png Two_sample_test-neg.png
convert -negate TwoSample_Test.png TwoSample_Test-neg.png
convert -negate Two-Way-Anova-Data1.png Two-Way-Anova-Data1-neg.png
convert -negate Type-I-II-OneSided-2.png Type-I-II-OneSided-2-neg.png
convert -negate Type-I-II-OneSided-3.png Type-I-II-OneSided-3-neg.png
convert -negate Type-I-II-OneSided-4.png Type-I-II-OneSided-4-neg.png
convert -negate Type-I-II-OneSided.png Type-I-II-OneSided-neg.png
convert -negate TypeI-II.png TypeI-II-neg.png
convert -negate Type-I-II-TwoSided-2.png Type-I-II-TwoSided-2-neg.png
convert -negate Type-I-II-TwoSided-3.png Type-I-II-TwoSided-3-neg.png
convert -negate Type-I-II-TwoSided-4.png Type-I-II-TwoSided-4-neg.png
convert -negate Type-I-II-TwoSided.png Type-I-II-TwoSided-neg.png
convert -negate Visualisation_mode_median_mean.svg.png Visualisation_mode_median_mean.svg-neg.png
convert -negate Wildlife.png Wildlife-neg.png
convert -negate XKCD_Seashell.png XKCD_Seashell-neg.png

convert -negate ./Fisher-Intro.png ./Fisher-Intro-neg.png


convert -negate Addressing-Field-Variability-with-Blocking_imagelarge.jpg Addressing-Field-Variability-with-Blocking_imagelarge-neg.jpg
convert -negate alpha-2beta.jpg alpha-2beta-neg.jpg
convert -negate Anova_Table2.jpg Anova_Table2-neg.jpg
convert -negate Anova_Table3.jpg Anova_Table3-neg.jpg
convert -negate Anova_Table.jpg Anova_Table-neg.jpg
convert -negate boxplot.jpg boxplot-neg.jpg
convert -negate Datasarous.jpg Datasarous-neg.jpg
convert -negate experimental-design-cartoon.jpg experimental-design-cartoon-neg.jpg
convert -negate Iris_Dataset_Fisher.jpg Iris_Dataset_Fisher-neg.jpg
convert -negate John_Tukey.jpg John_Tukey-neg.jpg
convert -negate Mean_Median_Mode.jpg Mean_Median_Mode-neg.jpg
convert -negate one-sided-test.jpg one-sided-test-neg.jpg
convert -negate Pearson_quote.jpg Pearson_quote-neg.jpg
convert -negate Types+of+Variable+with+respect+to+data.jpg Types+of+Variable+with+respect+to+data-neg.jpg
convert -negate xkcd_Curve_fitting2.jpg xkcd_Curve_fitting2-neg.jpg
convert -negate xkcd_Curve_fitting.jpg xkcd_Curve_fitting-neg.jpg
convert -negate MeaoStat.jpeg MeaoStat-neg.jpeg
convert -negate MM.jpeg MM-neg.jpeg
convert -negate MM_twocolors.jpeg MM_twocolors-neg.jpeg

convert -negate Beta_distribution_pdf.svg Beta_distribution_pdf-neg.svg
convert -negate Normal_Distribution_PDF.svg Normal_Distribution_PDF-neg.svg
